---

volumes:
  psql-data:

services:
  mcp_sse_server:
    container_name: mcp_sse_server
    env_file:
      - .env
    build:
      context: app/mcp_servers
      dockerfile: Dockerfile
    # volumes:
    #   - ./:/code
    ports:
      - 8000:8000
    restart: always
    environment:
      TRANSPORT_TYPE: sse
      POST_MODE: 'false'
    networks:
      data-lake-network: 

networks:
  data-lake-network: 
